#!/bin/bash

# Script que recibe por linea de comandos nombres
# o direcciones IP de servidores. Este muestra el UPTIME de la máquina
# para cada una de las maquinas introducidas. Si no pudiera, será notificado 
# entre un error producido porque la máquina no esté disponible, o porque la
# máquina no tiene activo el SSH. El script puede recibir el usuario a traves 
# de la opcion optativa "-u", si no se proporciona, se tomará el nombre del
# usuario que actualmente ha ejecutado el script.

if ! [[ $# > 0 ]]; then
	echo "Uso: `basename $0` [-u usuario] (máquinas)"
	echo "AYUDA:"
	echo "  - [] Estas opciones son opcionales"
	echo "  - () Estas opciones son obligatorias"
	echo "EJEMPLOS:"
	echo "  - `basename $0` -u admin 144.91.91.49 ..."
	echo "  - `basename $0` 172.16.11.{1..50}"
	echo "  - `basename $0` 192.168.1.5 marca.com 172.16.11.2"
	exit 1
elif [[ $( echo $1) == "-u" ]]; then
	usuarioMenosU=$2
	shift 2
fi

which nmap &>/dev/null

if [[ $? = 1 ]]; then
	read -p "Necesita instalar nmap para proceder [s/n]: " instalar
	if [[ $instalar = n ]] ; then
		exit 0
	elif [[ $instalar = s ]]; then
		sudo apt install nmap -y 2>/dev/null
		if [[ $? != 0 ]]; then
			echo "No dispone de los permisos suficientes, saliendo..."
			exit 1
		fi
	else
		echo "Debe introducir una opcion válida"
		exit 1
	fi
fi

for maquina in $(echo $@); do
	ping -w 1 $maquina &>/dev/null
	if [[ $? -ne 0 ]]; then
		echo
		echo "Máquina $maquina no disponible"
		echo
	elif [[ $(echo `nmap -sT $maquina | grep ssh | cut -d" " -f 1`) == "22/tcp" ]]; then
		upeo=$(ssh ${usuarioMenosU:-$(whoami)}@$maquina uptime -p)
		echo "$maquina lleva ... $upeo"
		echo
	else
		echo "Máquina $maquina SSH NO DISPONIBLE"

	fi

done

exit 0

